# Site settings
# These are used to personalize your new site.
title: Andrew Thompson # your name here
logo: "/images/palm.png" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  Professional Portfolio
  <br /><br />
  <a href="http://www.linkedin.com/in/andrew-thompson-63961018b">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  andrewthompson2 # update with your username
google_analytics: # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

